-- 즐겨찾기가 가장 많은 식당 정보 출력하기

-- 1. 테이블 하나 더 생성 X
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) = (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;

-- 2. 테이블 하나 더 생성 O
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES = (
    SELECT MAX(FAVORITES)
    FROM REST_INFO AS R2
    WHERE R2.FOOD_TYPE = REST_INFO.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;

-- 3. 서브쿼리 활용
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO AS R
WHERE FAVORITES = (
    SELECT MAX(FAVORITES)
    FROM REST_INFO
    WHERE FOOD_TYPE = R.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;