-- 오랜 기간 보호한 동물(2)

-- 1. MySQL용
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O
JOIN ANIMAL_INS AS I
    ON O.ANIMAL_ID = I.ANIMAL_ID
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2;

-- 2. Oracle, PostgreSQL용
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O
JOIN ANIMAL_INS AS I
    ON O.ANIMAL_ID = I.ANIMAL_ID
ORDER BY (O.DATETIME - I.DATETIME) DESC
LIMIT 2;